---
title: "Collecting the Qualitative Data Used in this Project"
author: "Adrien Ratsimbaharison"
date: "10/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Collecting Qualitative Data from Webpages Using the `rvest package`

For the most part, I use the `rvest package` for collecting the qualitative data used in this project. These qualitative data are the saved in the folder `qualitativeData` and then analyzed with the `RQDA package`.


### Biography of Andry Rajoelina from Wikipedia

```{r}
library(rvest)
library(xml2)

Url <- "Source: https://en.wikipedia.org/wiki/Andry_Rajoelina"

web_page <- read_html("https://en.wikipedia.org/wiki/Andry_Rajoelina")
# extracting the header
header <- web_page %>%
        html_nodes("h1") %>%
        html_text()

# extracting the text
text <- web_page %>%
        html_nodes("p") %>%
        html_text()

# saving the text to a local repository

andryRajoelinaBio1 <- writeLines(c(header, Url, text), "qualitativeData/andryRajoelinaBio1.txt")

```


 